const genres = [
  "Adventure",
  "African-American Studies",
  "Art",
  "Banned Books",
  "Biography",
  "Business",
  "Canadian Literature",
  "Classic",
  "Computers",
  "Cooking",
  "Correspondence",
  "Creative Commons",
  "Criticism",
  "Drama",
  "Espionage",
  "Essays",
  "Etiquette",
  "Fantasy",
  "Fiction and Literature",
  "Games",
  "Gay/Lesbian",
  "Ghost Stories",
  "Gothic",
  "Government Publication",
  "Harvard Classics",
  "Health",
  "History",
  "Horror",
  "Humor",
  "Instructional",
  "Language",
  "Music",
  "Mystery/Detective",
  "Myth",
  "Nature",
  "Nautical",
  "Non-fiction",
  "Occult",
  "Periodical",
  "Philosophy",
  "Pirate Tales",
  "Poetry",
  "Politics",
  "Post-1930",
  "Psychology",
  "Pulp",
  "Random Selection",
  "Reference",
  "Religion",
  "Romance",
  "Satire",
  "Science",
  "Science Fiction",
  "Sexuality",
  "Short Story",
  "Short Story Collection",
  "Thriller",
  "Travel",
  "War",
  "Western",
  "Women's Studies",
  "Young Readers",
];

module.exports = { genres };
